[pytest]
addopts = -v --strict-markers
testpaths = .
python_files = test_*.py

markers =
    smoke: basic smoke tests

log_cli = true
log_cli_level = INFO
log_file = pytest.log
log_file_level = INFO